### ISSUE TITLE
Error when trying to execute npm start

### ISSUE THREAD

**Issue by LaGhyoute** [zgwnu/test-ng-bonita#1]
I'm getting errors when trying to start the test application

> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "run" "cfg:dev"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! zgwnu-ng-bonita-test@1.0.0 cfg:dev: `cp cfg/dev/*.* dest`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the zgwnu-ng-bonita-test@1.0.0 cfg:dev script 'cp cfg/dev/*.*
>  dest'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the zgwnu-ng-bonita-test
> package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     cp cfg/dev/*.* dest
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs zgwnu-ng-bonita-test
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls zgwnu-ng-bonita-test
> npm ERR! There is likely additional logging output above.
>
> npm ERR! Please include the following file with any support request:
> npm ERR! D:\Projects\ng-test-bonita\test-ng-bonita\npm-debug.log
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! zgwnu-ng-bonita-test@1.0.0 prestart: `npm run build:dev && npm run cfg:
> dev && npm run cpx:dev`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the zgwnu-ng-bonita-test@1.0.0 prestart script 'npm run build
> :dev && npm run cfg:dev && npm run cpx:dev'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the zgwnu-ng-bonita-test
> package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run build:dev && npm run cfg:dev && npm run cpx:dev
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs zgwnu-ng-bonita-test
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls zgwnu-ng-bonita-test
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! D:\Projects\ng-test-bonita\test-ng-bonita\npm-debug.log
>

**Comment by onnohaldar** [comment]
**Repaired** by changing all Unix/Linux specific **"cp"** commands to generic _NPM CPX CLI_ based **"cpx"** commands. Now all the _NPM SCRIPTS_ must also work on a WINDOWS based Environment.

**Comment by LaGhyoute** [comment]
Thank you it's working.
